IF NOT (EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = 'FREELANCER' ))
BEGIN
CREATE DATABASE FREELANCER;
END
GO

IF OBJECT_ID (N'[dbo].[User]', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[User](
		UserId INT IDENTITY(1,1),
		UserName NVARCHAR(50),
		PasswordHash VARBINARY(MAX),
		PasswordSalt VARBINARY(MAX),
		FirstName NVARCHAR(50),
		LastName NVARCHAR(50),
		Email NVARCHAR(MAX),
		Phone NVARCHAR(15),
		PRIMARY KEY CLUSTERED(UserID ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  
		) ON [PRIMARY]  
END
GO

IF OBJECT_ID (N'Role', N'U') IS NULL 
BEGIN
	CREATE TABLE Role(
		RoleId INT IDENTITY(1,1),
		Name NVARCHAR(50),
		PRIMARY KEY CLUSTERED(RoleId ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  
		) ON [PRIMARY]  
END
GO

IF OBJECT_ID (N'UserRole', N'U') IS NULL 
BEGIN
	CREATE TABLE UserRole(
		Id INT IDENTITY(1,1),
		UserId INT,
		RoleId INT ,
		IsActive BIT DEFAULT(1),
		PRIMARY KEY CLUSTERED(Id ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  
		) ON [PRIMARY]  
END
GO