IF NOT (EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = 'FREELANCER' ))
BEGIN
CREATE DATABASE FREELANCER;
END
GO

IF OBJECT_ID (N'Account', N'U') IS NULL 
BEGIN
	CREATE TABLE Account(
		AccountID INT IDENTITY(1,1),
		UserName NVARCHAR(50),
		PasswordHash VARBINARY(MAX),
		PasswordSalt VARBINARY(MAX),
		FirstName NVARCHAR(50),
		LastName NVARCHAR(50),
		Email NVARCHAR(MAX),
		Phone NVARCHAR(15),
		PRIMARY KEY CLUSTERED(AccountID ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  
		) ON [PRIMARY]  
END
GO